name: Trigger auto deployment for ca-robojuggle-adagent-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ca-robojuggle-adagent-api-AutoDeployTrigger-d780a8fb-8c75-432d-be69-b96da182cf63.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CAROBOJUGGLEADAGENTAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CAROBOJUGGLEADAGENTAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CAROBOJUGGLEADAGENTAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUrl: acrrobojuggleadagent.azurecr.io
          registryUsername: ${{ secrets.CAROBOJUGGLEADAGENTAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAROBOJUGGLEADAGENTAPI_REGISTRY_PASSWORD }}
          containerAppName: ca-robojuggle-adagent-api
          resourceGroup: rg-robojuggle-adagent-prod-eastus-001
          imageToBuild: acrrobojuggleadagent.azurecr.io/ca-robojuggle-adagent-api:${{ github.sha }}
